### ISSUE TITLE
stack-chain warning when trace + clarify used together

### ISSUE THREAD

**Issue by StreetStrider** [AndreasMadsen/stack-chain#3]
Hello. I use `trace` + `clarify`, as it was described in [example](https://www.npmjs.com/package/trace#example). It works, but shows an error `Another copy of stack-chain was found, using the first initialized copy`. I've found this error origin and it appears when [multiple stack-chain modules are used](https://github.com/AndreasMadsen/stack-chain/blob/5686c81b1b15d0d3040e74844ff2cb0a87eabe1c/stack-chain.js#L41-L43).

The meaning of this error is clear to me, but I do not understand why this is necessary at all. Using of multiple modules is an essence of stack-chain, so this message is caused by pretty ordinary use-case.
Since every module [requires stack-chain by itself](https://github.com/AndreasMadsen/clarify/blob/14752eaa0b580fae4de35e0960a5dbc4530b43f8/clarify.js#L6) (we can't explicitly pass stack-chain instance to required modules) this message will occur any time more than one module is used where no real error is happen.

Please, can you explain why this message is required? I'm planning to use this module in some CLI utility, so this message will garbage my output. For now the only workaround I see is to replace `console.error` with fake one, init stack-chain modules, then restore `console.error`.

**Comment by AndreasMadsen** [comment]
Yeah doing the `console.error` is silly. I have a special development setup for this, where they use the same `stack-chain` module, but obviously this is not the normal setup.

But handling multiply copies is still obviously. The reason is that v8 don't support having multiply hooks into the `error.stack` string generation. It works by setting the properly `Error.prepareStackTrace` (see https://github.com/AndreasMadsen/stack-chain/blob/master/stack-chain.js#L152), which obviously can only be set once. Thus if copies of this module exists, they will conflict by overwriting the `Error.prepareStackTrace` property. The purpose of this module is actually to allow multiply hooks.

**Comment by AndreasMadsen** [comment]
I have published a new version of `stack-chain` where it is silent when there is multiply copies of the same version.

**Comment by StreetStrider** [comment]
@AndreasMadsen, thanks for reply. I'll stick to new version. This might be not a big issue for servers, but may be frustrating for packages like REPLs, loggers, monitors etc.
